### PR TITLE
Handle HTTP response codes 201 (Create) and 204 (No Content) as succesful responses.

### PR DESCRIPTION
**Pull request by jpe42**

### CODE REVIEW

**Comment by timmolter** [comment]
I believe @mmazi is on vacation or something. He'll definitely respond as soon as he sees this, I'm sure.

**Comment by jpe42** [comment]
Sure no worries.  After this Justcoin stuff I'd like to help out with the raw/generic migration, but doubt I will be motivated enough to do MtGox.  I'm surprised at how much XChange activity there is related to it given that it appears to be dying because of the lack of ability to transfer fiat out.

**Comment by timmolter** [comment]
That'd be great if you could help. Which exchange would you be motivated to do?? 

On another note, hopefully mmazi will return soon. And on another note, you should let @veken0m know about your new module, and he'll most likely plop it into Bitcoinium.

**Comment by jpe42** [comment]
I think I will take a stab at Kraken and also get the trade history working.  Will do on the Bitcoinium.

**Comment by timmolter** [comment]
@jamespedwards42 https://github.com/timmolter/XChange/issues/278

**Comment by mmazi** [comment]
Oops, I only saw this pull request now (after having already pushed https://github.com/mmazi/rescu/commit/4150dc3394dafa37bb2d1c3c1e7251bec88ba0a3). I'll check it out in a moment.

**Comment by mmazi** [comment]
Merged. I changed the code a bit -- @jamespedwards42, please see if this does what you need!

**Comment by jpe42** [comment]
Looks good.  I just tested against the new Justcoin demo with the rescu 1.5.1-SNAPSHOT jar and everything is working as expected.

**Pull request merged**
