### PR TITLE
Extended configuration options (HTTPS, Jackson, etc.) + bugfixes

### PR DESCRIPTION
**Pull request by martinzima**
-Extended the configuration options with ability to set the properties per proxy instance (not globally), HTTPS verification overrides and Jackson configuration listeners.
-Fixed Path parameters replacing when using regex matchers in interface definitions.
-Path parameters are now correctly resolved from the class annotations too.

### CODE REVIEW

**Comment by mmazi** [comment]
@reddragcz  thanks, this looks great!

Regarding the path parameter fixes, could you by any chance provide a test case or two that fails before your changes and passes after the changes? Or if you could just describe it in a sentence or two, and I'll implement it. Thanks!

**Comment by martinzima** [comment]
Yeah, I already thought about that. WIll provide test cases in a few hours when I get home.

**Comment by mmazi** [comment]
Great, thanks! If you don't have the time, just a few pointers will do and I'll implement them

**Comment by martinzima** [comment]
I have modified and committed the unit tests to reflect the changes, they would fail with the previous library version now. 

Basically it's about 

1) having path parameters specified even in the root interface path, e.g.:

```
@Path("api/{version}")
public interface ExampleService {
```

2) ability to postfix any path parameter with regex matcher for it, e.g.

```
@GET
    @Path("{ident: [a-Z]+}_{currency}/ticker")
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    Object getTicker(@PathParam("ident") String tradeableIdentifier, @PathParam("currency") String currency);
```

(See the ident parameter)
Note that with the changes I've made we won't support more complex regex matchers having the escaped "}" character itself in it as it would require a more complicated pattern in Params.applyToPath, but I guess that won't be an issue for now.

**Comment by mmazi** [comment]
@reddragcz Perfect, thanks a lot for the contribution!

**Pull request merged**
