### PR TITLE
Rename javax.ws.rs-api to jakarta.ws.rs-api and bump version from 2.1.1 to 2.1.5

### LINKED ISSUE #120: Update jakarta.ws.rs-api to fix building projects using xchange with sbt
This is the problem that I have when building a Scala project with sbt that's using Xchange: https://github.com/eclipse-ee4j/jaxrs-api/issues/572

It was possible to add a workaround by adding explicit dependency like this:
```
"javax.ws.rs" % "javax.ws.rs-api" % "2.1" artifacts Artifact("javax.ws.rs-api", "jar", "jar")
```

But this will stop working with sbt 1.3.0, in the issue linked above it says that the fix is to simply upgrade to newer version fo `jaxrs-api`, also there's a update to artifact name and group, see: https://github.com/eclipse-ee4j/jaxrs-api/issues/572#issuecomment-442445619

After the fix is merged and applied, Xchange will need to be updated to use new release of rescu

### PR DESCRIPTION
**Pull request by wlk**
fixes https://github.com/mmazi/rescu/issues/120

### CODE REVIEW

**Comment by mmazi** [comment]
Thanks for the PR.

Can you provide a reference about *why* the package should be changed from javax to jakarta?

Also, why use an old version and not the latest? 
https://mvnrepository.com/artifact/jakarta.ws.rs/jakarta.ws.rs-api

I'll merge this quickly and then release rescu probably some time next week, but please clarify these issues.

**Comment by wlk** [comment]
Hi,
Since 2.1.4 projects were renamed, see: https://projects.eclipse.org/projects/ee4j.jaxrs/releases/2.1.4/review and https://github.com/eclipse-ee4j/jaxrs-api/issues/572#issuecomment-442445619
and here: https://github.com/eclipse-ee4j/jaxrs-api/blob/master/jaxrs-api/pom.xml#L23 (the rs-api source code)

I'm using 2.1.5 which is the latest published, please correct if I'm wrong

**Comment by mmazi** [comment]
Ok thanks, sorry I was sloppy when checking.

Merging now. I'll release after some other issues have been also fixed, specifically #119 and perhaps some others.

**Comment by wlk** [comment]
Thanks :)

**Pull request merged**
