### PR TITLE
debug logging of request/response 

### PR DESCRIPTION
**Pull request by PavelNiedoba**
Modified logging so better fit production by adding DEBUG, which logs responses truncated at some maximum length so it don't bloat the logs

### CODE REVIEW

**Comment by mmazi** [comment]
Nice, thanks!

I'll merge this immediately when fixes are done.

**Comment by PavelNiedoba** [comment]
I'm not sure abut what fixes you talking about ? Shall I fix something ?

**Comment by mmazi** [comment]
I wrote some comments on the code on the GitHub Pull Request page. I suggested small improvements, please review. Thanks!

**Comment by PavelNiedoba** [comment]
can't see any comments,  feel free to make changes

**Comment by mmazi** [comment]
I'm not sure why you can't see my suggestions. They are not visible if you are not logged in, but you must have been logged in to make the above comment. They are visible to me [here](https://github.com/mmazi/rescu/pull/117/files) and also on this discussion page. Attaching a screenshot.

Screenshot 2020-05-19 at 07 38 27

**Comment by PavelNiedoba** [comment]
I dont know why your comments are not showing to me. It should be enabled

image

but theres nothing  i can see in the code

image

I did your sugestions according the screenshot

**Comment by mmazi** [comment]
Javadocs for responseMaxLogLen and requestMaxLogLen still seem to be incorrect (request/response swapped).

**Comment by PavelNiedoba** [comment]
fixed

**Pull request merged**
